name: Pull Request

on:
  branches:
    - main
  pull_request:
    types: [labeled]
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout gethub
        uses: actions/checkout@v2
      - name: Payload
        run: ${{github.event.pull_request.labels}}