name: Pull Request By Label
on:
  label:
    types: 
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gethub
        uses: actions/checkout@v2
      - name: Payload
        env : { EVENT : "${{ toJSON(github.event }}" }
        run: "echo $EVENT"