name: Pull Request By Label
on:
  pull_request:
    types: 
      - labeled
    branches:
      - main
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout gethub
        uses: actions/checkout@v2
      - name: Payload
        run: ${{github.event.pull_request.labels}}