name: Pull Request By Label
on:
  label:
    types: 
      - labeled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gethub
        uses: actions/checkout@v2
      - name: Payload
        run: echo ${{toJSON(github.event.pull_request.labels)}}